version: "3"

services:
    react-app:
        container_name: react-app
        build: ./client
        environment:
          WATCHPACK_POLLING: "true"
        stdin_open: true
        ports: 
          - "3000:3000"
        networks:
          - mern-app  
        volumes:
          - ./client/:/usr/src/app
          - /usr/src/app/node_modules
    api-server:
        container_name: api-server
        command: npm run dev
        build: ./
        ports:
          - "5000:5000"
        networks:
          - mern-app
        volumes:
          - ./:/usr/src/app
          - /usr/src/app/node_modules
        depends_on:
          - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
          - "27017:27017"
        networks:
          - mern-app
        environment:
            MONGO_INITDB_ROOT_USERNAME: altion
            MONGO_INITDB_ROOT_PASSWORD: altion2022
        volumes:
          - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data: 
    driver: local