from funciones import AuxiliarFunctions 
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select


def navegationLogin():
    AuxiliarFunctions.driver.get("http://192.168.1.100:3000/")
    AuxiliarFunctions.waitFiveSeconds()
    btnRegister = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/section/main/a")
    btnRegister.click()
    AuxiliarFunctions.waitFiveSeconds()
    btnLogin = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/section/main/p[2]/span/a")
    btnLogin.click()
    AuxiliarFunctions.waitFiveSeconds()

def navegationPointsCEVEMP():
    btnNewPoint = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[2]/a")
    btnNewPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromPoints = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromPoints.click()
    AuxiliarFunctions.waitFiveSeconds()

def navegationChoferes():
    BtnGoToChoferes = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[3]/a") 
    BtnGoToChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToNewChoferes = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg") 
    BtnGoToNewChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromNewChoferes = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path") 
    BtnBackFromNewChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGotoModifyChoferes  = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > div > table > tbody > tr > td:nth-child(3) > button > svg") 
    BtnGotoModifyChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromModifyChoferes = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path") 
    BtnBackFromModifyChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromChoferes = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromChoferes.click()
    AuxiliarFunctions.waitFiveSeconds()

def navegationUsers():
    BtnGoToUsers = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[2]/a") 
    BtnGoToUsers.click()
    AuxiliarFunctions.waitFiveSeconds() 
    BtnGoToNewUsers = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnGoToNewUsers.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromNewUsers = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromNewUsers.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToModifyUsers = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > button > svg > path")
    BtnGoToModifyUsers.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromModifyUsers = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromModifyUsers.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromUsers = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromUsers.click()
    AuxiliarFunctions.waitFiveSeconds()

def navegationAdminPoints():
    BtnGoToCEVPoints = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[5]/a") 
    BtnGoToCEVPoints.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToNewCEVPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnGoToNewCEVPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromNewCEVPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg")
    BtnBackFromNewCEVPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToModifyCEVPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > div > table > tbody > tr > td:nth-child(6) > button > svg > path")
    BtnGoToModifyCEVPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromModifyCEVPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromModifyCEVPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromCEVPoints = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromCEVPoints.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToEMPPoints = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[6]/a") 
    BtnGoToEMPPoints.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToNewEMPPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnGoToNewEMPPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromNewEMPPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg")
    BtnBackFromNewEMPPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToModifyEMPPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > div > table > tbody > tr > td:nth-child(6) > button > svg")
    BtnGoToModifyEMPPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromModifyEMPPoint = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromModifyEMPPoint.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromEMPPoints = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromEMPPoints.click()
    AuxiliarFunctions.waitFiveSeconds()

def navegationZones():
    BtnGoToZones = AuxiliarFunctions.driver.find_element(By.XPATH,"/html/body/div/div/section/p[4]/a") 
    BtnGoToZones.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToNewZones = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnGoToNewZones.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromNewZones = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromNewZones.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnGoToModifyZones = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > div > table > tbody > tr > td:nth-child(3) > button > svg")
    BtnGoToModifyZones.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromModifyZones = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(1) > svg > path")
    BtnBackFromModifyZones.click()
    AuxiliarFunctions.waitFiveSeconds()
    BtnBackFromZones = AuxiliarFunctions.driver.find_element(By.CSS_SELECTOR,"#root > header > div > nav > button:nth-child(2) > svg") 
    BtnBackFromZones.click()
    AuxiliarFunctions.waitFiveSeconds()